import os
import pygame

#GAME CONSTANTS
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 800
RATIO = SCREEN_HEIGHT/240
BACKGROUND_WIDTH, BACKGROUND_HEIGHT = int(3400*RATIO), int(240*RATIO)
TILE_SIZE = int(16*RATIO)
PATH = os.getcwd()
PATH = os.path.join(PATH, PATH + '\Images')
