import os

#GAME CONSTANTS
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 800
RATIO = SCREEN_HEIGHT/240
BACKGROUND_WIDTH, BACKGROUND_HEIGHT = int(3400*RATIO), int(240*RATIO)
TILE_SIZE = int(16*RATIO)
PATH = os.getcwd()
PATH = os.path.join(PATH, PATH + '\Images')

#SPRITE CONSTANTS
PIPES_POSITION = [] #[[size, pos_x, pos_y]]
CLOUD_POSITIONS = []
BRICK_POSITIONS=[(0, 0)]
BRICK_POSITIONS = [(pos[0]*TILE_SIZE, pos[1]*TILE_SIZE) for pos in BRICK_POSITIONS]
STAIRS_POSITION = []
COIN_POSITIONS = []


#CHARACTER CONSTANTS
STARTING_POSITION = (5*TILE_SIZE, SCREEN_HEIGHT - 3*TILE_SIZE)
VELOCITY = 1
Y_VELOCITY = 3
GRAVITY = -2
PEACH_POS = (0, 0) #TBD

